version: '3'
services:
  goimports:
    build:
      context: ./scripts/meta
      dockerfile: goimports.Dockerfile
  generate:
    build:
      context: ./scripts/meta
      dockerfile: generate.Dockerfile
    command: [ruby, /usr/src/meta/generate.rb]
    volumes:
      - ./pkg/coinbasepro:/usr/src/coinbasepro
      - ./pkg/morningstar:/usr/src/morningstar
      - ./pkg/polygon:/usr/src/polygon
      - ./pkg/twitter:/usr/src/twitter
      - ./scripts/meta/comment.rb:/usr/src/meta/comment.rb
      - ./scripts/meta/path.rb:/usr/src/meta/path.rb
      - ./scripts/meta/endpoint.rb:/usr/src/meta/endpoint.rb
      - ./scripts/meta/field.rb:/usr/src/meta/field.rb
      - ./scripts/meta/generate.rb:/usr/src/meta/generate.rb
      - ./scripts/meta/schema:/usr/src/meta/schema
      - ./scripts/meta/model_writer.rb:/usr/src/meta/model_writer.rb
      - ./scripts/meta/go_http.rb:/usr/src/meta/go_http.rb
      - ./scripts/meta/go_client.rb:/usr/src/meta/go_client.rb
      - ./scripts/meta/model_unmarshaler.rb:/usr/src/meta/model_unmarshaler.rb
      - ./scripts/meta/go_struct.rb:/usr/src/meta/go_struct.rb
      - ./scripts/meta/setters.rb:/usr/src/meta/setters.rb
      - ./scripts/meta/option.rb:/usr/src/meta/option.rb
      - ./scripts/meta/path_part.rb:/usr/src/meta/path_part.rb
      - ./scripts/meta/scheme.rb:/usr/src/meta/scheme.rb
      - ./scripts/meta/path_writer.rb:/usr/src/meta/path_writer.rb
      - ./scripts/meta/inflector.rb:/usr/src/meta/inflector.rb
      - ./scripts/meta/types.rb:/usr/src/meta/types.rb
      - ./scripts/meta/enum.rb:/usr/src/meta/enum.rb
      - ./scripts/meta/types_writer.rb:/usr/src/meta/types_writer.rb
      - ./scripts/meta/ratelimiter.rb:/usr/src/meta/ratelimiter.rb
      - ./scripts/meta/ratelimiter_writer.rb:/usr/src/meta/ratelimiter_writer.rb
      - ./scripts/meta/const.rb:/usr/src/meta/const.rb
    depends_on:
      - goimports
  test_generate:
    build:
      context: ./scripts/meta
      dockerfile: generate.Dockerfile
    command: [ruby, /usr/src/meta/test/test.rb]
    volumes:
      - ./pkg/coinbasepro:/usr/src/coinbasepro
      - ./pkg/morningstar:/usr/src/morningstar
      - ./pkg/polygon:/usr/src/polygon
      - ./pkg/twitter:/usr/src/twitter
      - ./scripts/meta/comment.rb:/usr/src/meta/comment.rb
      - ./scripts/meta/path.rb:/usr/src/meta/path.rb
      - ./scripts/meta/endpoint.rb:/usr/src/meta/endpoint.rb
      - ./scripts/meta/field.rb:/usr/src/meta/field.rb
      - ./scripts/meta/generate.rb:/usr/src/meta/generate.rb
      - ./scripts/meta/schema:/usr/src/meta/schema
      - ./scripts/meta/model_writer.rb:/usr/src/meta/model_writer.rb
      - ./scripts/meta/go_http.rb:/usr/src/meta/go_http.rb
      - ./scripts/meta/go_client.rb:/usr/src/meta/go_client.rb
      - ./scripts/meta/model_unmarshaler.rb:/usr/src/meta/model_unmarshaler.rb
      - ./scripts/meta/go_struct.rb:/usr/src/meta/go_struct.rb
      - ./scripts/meta/setters.rb:/usr/src/meta/setters.rb
      - ./scripts/meta/option.rb:/usr/src/meta/option.rb
      - ./scripts/meta/path_part.rb:/usr/src/meta/path_part.rb
      - ./scripts/meta/scheme.rb:/usr/src/meta/scheme.rb
      - ./scripts/meta/test:/usr/src/meta/test
      - ./scripts/meta/path_writer.rb:/usr/src/meta/path_writer.rb
      - ./scripts/meta/inflector.rb:/usr/src/meta/inflector.rb
      - ./scripts/meta/types.rb:/usr/src/meta/types.rb
      - ./scripts/meta/enum.rb:/usr/src/meta/enum.rb
      - ./scripts/meta/types_writer.rb:/usr/src/meta/types_writer.rb
      - ./scripts/meta/ratelimiter.rb:/usr/src/meta/ratelimiter.rb
      - ./scripts/meta/ratelimiter_writer.rb:/usr/src/meta/ratelimiter_writer.rb
      - ./scripts/meta/const.rb:/usr/src/meta/const.rb
    depends_on:
      - goimports
