version: '3'
services:
  goimports:
    build:
      context: ./scripts/meta
      dockerfile: goimports.Dockerfile
  generate:
    build:
      context: ./scripts/meta
      dockerfile: generate.Dockerfile
    command: [ruby, /usr/src/meta/generate.rb]
    volumes:
      - ./pkg/coinbase:/usr/src/coinbase
      - ./scripts/meta/comment.rb:/usr/src/meta/comment.rb
      - ./scripts/meta/post_authority.rb:/usr/src/meta/post_authority.rb
      - ./scripts/meta/endpoint.rb:/usr/src/meta/endpoint.rb
      - ./scripts/meta/field.rb:/usr/src/meta/field.rb
      - ./scripts/meta/generate.rb:/usr/src/meta/generate.rb
      - ./scripts/meta/schema:/usr/src/meta/schema
      - ./scripts/meta/model.rb:/usr/src/meta/model.rb
      - ./scripts/meta/go_http.rb:/usr/src/meta/go_http.rb
      - ./scripts/meta/go_client.rb:/usr/src/meta/go_client.rb
      - ./scripts/meta/unmarshaller.rb:/usr/src/meta/unmarshaller.rb
      - ./scripts/meta/go_struct.rb:/usr/src/meta/go_struct.rb
      - ./scripts/meta/setters.rb:/usr/src/meta/setters.rb
      - ./scripts/meta/option.rb:/usr/src/meta/option.rb
      - ./scripts/meta/path_part.rb:/usr/src/meta/path_part.rb
      - ./scripts/meta/scheme.rb:/usr/src/meta/scheme.rb
      - ./scripts/meta/go_post_authority.rb:/usr/src/meta/go_post_authority.rb
    depends_on:
      - goimports
  test_generate:
    build:
      context: ./scripts/meta
      dockerfile: generate.Dockerfile
    command: [ruby, /usr/src/meta/test/test.rb]
    volumes:
      - ./pkg/coinbase:/usr/src/coinbase
      - ./scripts/meta/comment.rb:/usr/src/meta/comment.rb
      - ./scripts/meta/post_authority.rb:/usr/src/meta/post_authority.rb
      - ./scripts/meta/endpoint.rb:/usr/src/meta/endpoint.rb
      - ./scripts/meta/field.rb:/usr/src/meta/field.rb
      - ./scripts/meta/generate.rb:/usr/src/meta/generate.rb
      - ./scripts/meta/schema:/usr/src/meta/schema
      - ./scripts/meta/model.rb:/usr/src/meta/model.rb
      - ./scripts/meta/go_http.rb:/usr/src/meta/go_http.rb
      - ./scripts/meta/go_client.rb:/usr/src/meta/go_client.rb
      - ./scripts/meta/unmarshaller.rb:/usr/src/meta/unmarshaller.rb
      - ./scripts/meta/go_struct.rb:/usr/src/meta/go_struct.rb
      - ./scripts/meta/setters.rb:/usr/src/meta/setters.rb
      - ./scripts/meta/option.rb:/usr/src/meta/option.rb
      - ./scripts/meta/path_part.rb:/usr/src/meta/path_part.rb
      - ./scripts/meta/scheme.rb:/usr/src/meta/scheme.rb
      - ./scripts/meta/test:/usr/src/meta/test
      - ./scripts/meta/go_post_authority.rb:/usr/src/meta/go_post_authority.rb
    depends_on:
      - goimports
